apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-cicd-app
  labels:
    app: eks-cicd-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-cicd-app
  template:
    metadata:
      labels:
        app: eks-cicd-app
      annotations:
        # This forces a new deployment every time the value changes
        deploy-timestamp: "BUILD_TIMESTAMP" 
    spec:
      containers:
      - name: eks-cicd-app
        image: ://amazonaws.com
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10

